server:
  port: 8082

spring:
  application:
    name: order-service
  cloud:
    # OpenFeign 配置
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
      circuitbreaker:
        enabled: true
    # Nacos 配置
    nacos:
      discovery:
        server-addr: 115.190.171.200:8848
        namespace: public
      config:
        enabled: false

# 日志配置
logging:
  level:
    com.example.order: DEBUG
