server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
