server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

  data:
    redis:
      port: 6379
      host: 111.229.106.212
      password: Shuai3198@
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
