server:
  port: 8083

spring:
  application:
    name: product-service
  cloud:
    # Nacos ??
    nacos:
      discovery:
        server-addr: 115.190.171.200:8848
        namespace: public
      config:
        enabled: false
        # server-addr: localhost:8848
        # file-extension: yaml
        # namespace: public
    # Sentinel ??
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
      eager: true
      web-context-unify: false
      feign:
        enabled: true  # ?? Feign ?? Sentinel

# OpenFeign ??
openfeign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

# ????
logging:
  level:
    com.example.order: DEBUG
