spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 111.229.106.212:8848
    sentinel:
      transport:
        dashboard: 111.229.106.212:8089
server:
  port: 8082
