server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 115.190.171.200:8848
        namespace: public
      config:
        enabled: false
    sentinel:
      transport:
        dashboard: 115.190.171.200:8729
        port: 8719
      eager: true
      web-context-unify: false
      feign:
        enabled: true

logging:
  level:
    com.example.user: DEBUG
