server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    # Nacos 配置
    nacos:
      discovery:
        server-addr: 115.190.171.200:8848
        namespace: public
      config:
        enabled: false
#        server-addr: 115.190.171.200:8848
#        file-extension: yaml
#        namespace: public
    # OpenFeign 配置
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
    # Sentinel 配置
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
      eager: true
      web-context-unify: false
      feign:
        enabled: true  # 开启 Feign 整合 Sentinel

# 日志配置
logging:
  level:
    com.example.user: DEBUG
