spring:
  application:
    name: spring-security-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://49.233.155.253:3306/db_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8"
    username: root
    password: 123456
  data:
    redis:
      host: 49.233.155.253
      port: 6379
      database: 0
      username: default
      password: 123456
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s

      # Lettuce 客户端的配置
      lettuce:
        # 连接池配置
        pool:
          # 最小空闲连接
          min-idle: 0
          # 最大空闲连接
          max-idle: 8
          # 最大活跃连接
          max-active: 8
          # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
          max-wait: -1ms

server:
  port: 8081


mybatis-plus:
  configuration:
    # 如果项目无日志框架，可以考虑指定为 org.apache.ibatis.logging.stdout.StdOutImpl (请勿在实际生产中使用).
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  access-expire: 1800000  # 30分钟，单位毫秒
  secret: secretKeyNotTellingYouSecretKeyNotTellingYou
  issuer: zms
  subject: Peripherals