spring:
  application:
    name: spring-security-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/db_02?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8"
    username: root
    password: 123456
server:
  port: 8081
